GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/667881566f93855e4120f693
###
DELETE  http://localhost:3001/api/persons/667881486f93855e4120f68f
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "phil",
    "number": "123456578" 
}