GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1
###
DELETE  http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "phil",
    "number": "123456578" // has to be number not phone
}